### ISSUE TITLE
Add tutorials

### ISSUE THREAD

**Issue by mehdy** [OSS-Hackathon/IranOpenSourceHackathon#1]
We need some tutorials about how to contribute to open source projects.

**Comment by negarjf** [comment]
I just start searching for any sort of tutorials for starting contribution in open source projects and hopefully, there are a lot of them. I've picked three different sources. Each source covers all a beginner contributor needs to know.
I'll leave a link to these resources here. Please give it a look and let me know if you have any opinions about them.

## Introduction to Open Source
A series of articles provided by _Digital Ocean Community_ : [🔗  Link](https://www.digitalocean.com/community/tutorial_series/an-introduction-to-open-source)
### Headlines:
- How To Contribute to Open Source: Getting Started with Git
- How To Create a Pull Request on GitHub
- How To Rebase and Update a Pull Request
- How To Maintain Open-Source Software Projects
- How To Use Git: A Reference Guide

## How to Contribute to Open Source
A series of articles provided by _Open Source Guides_ : [🔗  Link](https://opensource.guide/how-to-contribute/)
### Headlines:
- Why contribute to open source?
- What it means to contribute
- Orienting yourself to a new project
- Finding a project to contribute to
- How to submit a contribution
- What happens after you submit a contribution

## How to Contribute to an Open Source Project on GitHub
A 38 minutes video tutorial by _Kent C. Dodds on Egghead_: [🔗  Link](https://egghead.io/lessons/javascript-how-to-authenticate-with-github-using-ssh)
Showing all the necessary information about git and Github in action (For those who prefer video contents).

**Comment by loreanvictor** [comment]
@negarjf seems like a good stuff and not much discussion happening on this. Perhaps we should move forward by making a PR out of this?

**Comment by loreanvictor** [comment]
@negarjf seems like a good stuff and not much discussion happening on this. Perhaps we should move forward by making a PR out of this?
