### ISSUE TITLE
A tool to watch the contributions made to the repositories

### ISSUE THREAD

**Issue by mehdy** [OSS-Hackathon/IranOpenSourceHackathon#2]

**Comment by sina-mirhejazi** [comment]
Here

**Comment by loreanvictor** [comment]
can we make the script realize [this process](https://github.com/OSS-Hackathon/IranOpenSourceHackathon#how-can-i-participate)?

**Comment by mehdy** [comment]
R&D in progress.

**Comment by mehdy** [comment]
It seems like we can use a query like below to search for the PRs we want in the repos.
```
https://api.github.com/search/issues?q=<Identifier>+repo:{user}/{repo}+is:pr+in:title,body,comments
```
And people can mention the identifier in the title, body or comments.

**Comment by mehdy** [comment]
And for the `Identifier` I think `IranOpenSourceHackathon` is unique enough.

**Comment by loreanvictor** [comment]
> And for the `Identifier` I think `IranOpenSourceHackathon` is unique enough.

Wouldn't a long term like `IranOpenSourceHackathon` have a high chance of typos / mis-types as well? I think it would be a safer option to use a smaller keyword that is harder to make mistakes on (#iosh, #iroshack, etc.)
