### ISSUE TITLE
A simple website using GitHub pages

### ISSUE THREAD

**Issue by mehdy** [OSS-Hackathon/IranOpenSourceHackathon#3]

**Comment by mehdy** [comment]
ETA: Apr 16

**Comment by SamaneYaghoubi** [comment]
appreciate any comments
https://oss-hackathon.github.io/IranOpenSourceHackathon/

**Comment by loreanvictor** [comment]
@SamaneYaghoobi this looks really slick 😎

can we move the contents to the main branch though? generally `gh-pages` branch is used when the web-page is fully auto-generated and you wouldn't want to keep it version controlled alongside the rest of the repository, which is not the case here. additionally, if it was on the main branch, it would be much easier to have a script copy parts of the readme into the website (right now, the script needs to clone the repo, read the contents from the main branch, then switch the branch and apply them).

**Comment by SamaneYaghoubi** [comment]
@loreanvictor I think if we move it to the main branch, we couldn't have github pages link.
But if we don't need this link, i'm ok with this changes.

**Comment by loreanvictor** [comment]
> @loreanvictor I think if we move it to the main branch, we couldn't have github pages link.

That is not the case ([example](https://connect-platform.github.io/codedoc-boilerplate/)).
