### ISSUE TITLE
Add a series of terms and conditions

### ISSUE THREAD

**Issue by mehdy** [OSS-Hackathon/IranOpenSourceHackathon#4]

**Comment by mehdy** [comment]
Draft:
For Repository Maintainers
• Please be friendly and patient with the new contributors.
• Respond to the issues and PRs within 24 hours as long as it's possible.

For Individual Contributors
• Read the provided documents by the repositories to avoid common mistakes.
• Be sure to check the issues and PRs before submitting any to avoid spamming the repositories.
• Be friendly and respect the time and opinion of the maintainers.

• The core reason for holding these events is to encourage people to contribute to the open source community more often and easily by celebrating their efforts doing so.
• If we receive violation reports, we'll investigate and it may lead to being blocked from the program.
• In case of any dispute or disagreement, the directors of the program have the final saying.

**Comment by sina-mirhejazi** [comment]
For Individual Contributors
- Be sure to follow the same code style and conventions as the repository maintainers

**Comment by loreanvictor** [comment]
Seems not much discussion happening on this. @mehdy could you make a PR out of this?
