### ISSUE TITLE
Update Readme to reflect final rules

### ISSUE THREAD

**Issue by loreanvictor** [OSS-Hackathon/IranOpenSourceHackathon#51]
[This section](https://github.com/OSS-Hackathon/IranOpenSourceHackathon#how-can-i-participate) requires updating based on our current scoring scripts. We should also take out all **WORK-IN-PROGRESS** notices from the README now since everything is finalized.

**Comment by mehdy** [comment]
@loreanvictor It seems the link to "this section" is incorrect. I got the gist of it though!

**Comment by mehdy** [comment]
Updated the readme. Feel free to close the issue or raise any remaining issue.

**Comment by loreanvictor** [comment]
> Updated the readme. Feel free to close the issue or raise any remaining issue.

could you also comment out "⚠️⚠️ WORK IN PROGRESS NOTICE" section, since we no longer have any work in progress bits (and the work is further than WORK IN PROGRESS)?
