### ISSUE TITLE
Xeft companies for open-source repos

### ISSUE THREAD

**Issue by loreanvictor** [OSS-Hackathon/IranOpenSourceHackathon#8]
Talk to maintainers of repos of following companies. Also add other companies (official github profile).

- [Divar](https://github.com/divar-ir)
- [Snapp](https://github.com/snapp-cab)
- [Arvan](https://github.com/arvancloud?page=1)

**Comment by negarjf** [comment]
Here's Alibaba's Organization: [Alibaba Travels Co Open Source](https://github.com/alibaba-aero)

**Comment by SamaneYaghoubi** [comment]
[Sazito](https://github.com/Sazito)

**Comment by mehdy** [comment]
I'm communicating with Divar to add more repos
