### ISSUE TITLE
Create a poster for the event

### ISSUE THREAD

**Issue by loreanvictor** [OSS-Hackathon/IranOpenSourceHackathon#9]
So we can send it to maintainers and encourage them to bring in repos.

**Comment by loreanvictor** [comment]
timeframe: 15 tir - 15 shahrivar

**Comment by mehdy** [comment]
ETA: Apr 16

**Comment by loreanvictor** [comment]
So we've got 3 posters. Use them based on your preference (or considering the context you want to use the poster):

<div align="center">

## Formal Poster

<img src="https://raw.githubusercontent.com/OSS-Hackathon/IranOpenSourceHackathon/main/first/poster/svg/poster-1.svg" width="256px"/>
</div>

<br>

<div align="center">

## Geeky Poster

<img src="https://raw.githubusercontent.com/OSS-Hackathon/IranOpenSourceHackathon/main/first/poster/svg/poster-2.svg" width="256px"/>
</div>

<br>

<div align="center">

## Minimalist Poster

<img src="https://raw.githubusercontent.com/OSS-Hackathon/IranOpenSourceHackathon/main/first/poster/svg/poster-3.svg" width="256px"/>
</div>

**Comment by loreanvictor** [comment]
@mehdy @SamaneYaghoobi @sina-mirhejazi @negarjf @ebraminio @Ahmadb7 any comments on the designs?

**Comment by sina-mirhejazi** [comment]
Are we going to use all three or we have to select one? If the latter, I guess the geeky one is a little confusing for newbies. I'll vote for the first one, with one suggestion. Maybe it's better to use numbers on the Shamsi date for consistency.

**Comment by SamaneYaghoubi** [comment]
@loreanvictor I really like the geeky version, but I think it's better to write the complete URL in website address and don't split it.

**Comment by loreanvictor** [comment]
> Are we going to use all three or we have to select one? If the latter, I guess the geeky one is a little confusing for newbies. I'll vote for the first one, with one suggestion. Maybe it's better to use numbers on the Shamsi date for consistency.

Nah my idea was to use whichever version you like, so a poster for any taste (or any context).

**Comment by loreanvictor** [comment]
> @loreanvictor I really like the geeky version, but I think it's better to write the complete URL in website address and don't split it.

Well the URL unfortunately gets a little bit long, but will try to see what can I do.

**Comment by mehdy** [comment]
@loreanvictor Thanks, dude! This is amazing! 
I like all of them! and I probably will use all of them as well!

@SamaneYaghoobi isn't the QR code helpful enough for the complete URL?

**Comment by loreanvictor** [comment]
> Are we going to use all three or we have to select one? If the latter, I guess the geeky one is a little confusing for newbies. I'll vote for the first one, with one suggestion. Maybe it's better to use numbers on the Shamsi date for consistency.

p.s. the numbers on Iran Sans unfortunately are nowhere near as boxy as the characters (unlike Oxanium, which is the latin font used here), which results in a eye-soring visual contrast (thats why they are written).
